import type { NextPage } from 'next'
import Head from 'next/head'
import { useTheme } from 'next-themes'

const Home: NextPage = () => {
  const { theme } = useTheme()

  return (
    <div data-theme={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="my-3 font-serif">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className="flex gap-5 my-3">
          <button className="btn btn-info">info</button>
          <button className="btn btn-success">success</button>
          <button className="btn btn-warning">warning</button>
          <button className="btn btn-error">error</button>
        </div>

        <div className="my-3 alert alert-error">
          <div className="flex-1">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              className="mx-2 w-6 h-6 stroke-current"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"
              ></path>
            </svg>
            <p>Lorem ipsum dolor sit amet, consectetur adip!</p>
          </div>
        </div>

        <div className="my-3 w-96 shadow-md card bordered">
          <div className="card-body">
            <h2 className="card-title">Small image file</h2>
            <p>
              Rerum reiciendis beatae tenetur excepturi aut pariatur est eos. Sit sit necessitatibus veritatis sed
              molestiae voluptates incidunt iure sapiente.
            </p>
            <div className="card-actions">
              <div className="badge badge-ghost">Article</div>
              <div className="badge badge-ghost">Photography</div>
            </div>
          </div>
        </div>

        <p>
          Get started by editing <code>pages/index.tsx</code>
        </p>

        <div>
          <a href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/master/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by vercel
        </a>
      </footer>
    </div>
  )
}

export default Home
